# Generated by Django 4.0.3 on 2022-04-25 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_article_image_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Fotoğraf ekleyin.'),
        ),
    ]
