# Generated by Django 4.0.3 on 2022-04-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_alter_article_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
